import homodeus from '../assets/homo-deus.jpg';
import sapiens from '../assets/sapiens.jpg';
import licoes21 from '../assets/21-licoes.jpg';
import entendaGato from '../assets/entenda-gato.jpg';
import jojoManga from '../assets/jojo-manga.jpg';
import diarioAnne from '../assets/diario-anne.jpg';
import hyruleHistoria from '../assets/hyrule-historia.jpg';
import homemDeGiz from '../assets/homem-de-giz.jpg';
import duna from '../assets/duna.jpg';
import morroDosVentos from '../assets/morro-dos-ventos.jpg';
import starWars from '../assets/star-wars.jpg';
import deusesAmericanos from '../assets/deuses-americanos.jpg';

export default function mock(){

    return [
            {id:0, img: sapiens, titulo:'Sapiens', autor:'Yuval Noah Harari', preco:39.90, descricao:'"Um dos maiores fenômenos editoriais dos últimos tempos O que possibilitou ao Homo sapiens subjugar as demais espécies? O que nos torna capazes das mais belas obras de arte, dos avanços científicos mais impensáveis e das mais horripilantes guerras? Nossa capacidade imaginativa. Somos a única espécie que acredita em coisas que não existem na natureza, como Estados, dinheiro e direitos humanos. Partindo dessa ideia, Yuval Noah Harari, doutor em história pela Universidade de Oxford, aborda em Sapiens a história da humanidade sob uma perspectiva inovadora. Explica que o ca­pitalismo é a mais bem-sucedida religião; que o imperialismo é o sistema político mais lucrativo; que nós, humanos modernos, embora sejamos muito mais poderosos que nossos ancestrais, provavelmente não somos mais felizes. Um relato eletrizante sobre a aventura de nossa extraordinária espécie – de primatas insignificantes a senhores do mundo. “Uma história abrangente da raça humana. [...] aborda alguns dos fatores cruciais que nos permitiram construir esta extraordinária civilização.” - Barack Obama"'},
            {id:1, img: homodeus, titulo:'Homo Deus', autor:'Yuval Noah Harari', preco:64.90, descricao:'Neste “Homo Deus”: uma breve história do amanhã, Yuval Noah Harari, autor do estrondoso best-seller Sapiens: uma breve história da humanidade, volta a combinar ciência, história e filosofia, desta vez para entender quem somos e descobrir para onde vamos. Sempre com um olhar no passado e nas nossas origens, Harari investiga o futuro da humanidade em busca de uma resposta tão difícil quanto essencial: depois de séculos de guerras, fome e pobreza, qual será nosso destino na Terra? A partir de uma visão absolutamente original de nossa história, ele combina pesquisas de ponta e os mais recentes avanços científicos à sua conhecida capacidade de observar o passado de uma maneira inteiramente nova. Assim, descobrir os próximos passos da evolução humana será também redescobrir quem fomos e quais caminhos tomamos para chegar até aqui.'},   
            {id:2, img: licoes21, titulo:'21 Lições para o Século 21', autor:'Yuval Noah Harari', preco:59.90, descricao:'O novo livro do autor de Sapiens e Homo Deus explora as grandes questões do presente e o que podemos fazer para melhorálo. Como podemos nos proteger de guerras nucleares, cataclismos ambientais e crises tecnológicas? O que fazer sobre a epidemia de fake news ou a ameaça do terrorismo? O que devemos ensinar aos nossos filhos? Em Sapiens, Yuval Noah Harari mostrou de onde viemos; em Homo Deus, para onde vamos. 21 lições para o século 21 explora o presente e nos conduz por uma fascinante jornada pelos assuntos prementes da atualidade. Seu novo livro trata sobre o desafio de manter o foco coletivo e individual em face a mudanças frequentes e desconcertantes. Seríamos ainda capazes de entender o mundo que criamos?'},
            {id:3, img: entendaGato, titulo:'Entenda Seu Gato', autor:'Arden Moore', preco:37.00, descricao:'"Gatos são animais adoráveis, observadores e engraçados. Mas também podem ser teimosos, ariscos e irritantemente reservados. Embora tudo isso faça parte do charme deles, entender o que está por trás de cada comportamento é essencial para que a convivência entre dono e animal seja tranquila. Neste livro, Arden Moore, uma das principais consultoras sobre gatos dos Estados Unidos, decifra todas as atitudes e manias dos bichanos – por que arranham as coisas, se esfregam em nossa perna, ronronam, escalam cortinas, perseguem ratos, destroem a árvore de Natal e mastigam fios plásticos, por exemplo –, fornecendo conselhos valiosos para mantê-los saudáveis, seguros e felizes. Recheado de ilustrações, o livro conta ainda com orientações de veterinários, dicas práticas e curiosidades, além de histórias de pessoas que foram bem-sucedidas ao resolver problemas de comportamento de seus amigos felinos. Entenda seu gato é, em resumo, um manual imprescindível para todos aqueles que desejam conhecer a fundo esse universo tão complexo e encantador."'}, 
            {id:4, img: jojoManga, titulo:'JOJO: Phantom Blood', autor:'Hirohiko Araki', preco:29.90, descricao:'Jonathan é o herdeiro único de uma notória família da aristocracia britânica, os Joestar. Tudo o que o jovem queria era ser um cavalheiro e viver de forma tranquila e despreocupada. Porém, seus pacatos dias estão para acabar, pois a chegada do "invasor" Dio Brando fará tudo virar de cabeça para baixo. Além de sofrer diariamente nas mãos de Dio, ainda há a presença sombria de uma misteriosa Máscara de Pedra...'}, 
            {id:5, img: diarioAnne, titulo:'O Diário de Anne Frank', autor:'Anne Frank', preco:27.00, descricao:'A edição brochura de O diário de Anne Frank está de roupa nova O depoimento da pequena Anne Frank, morta pelos nazistas após passar anos escondida no sótão de uma casa em Amsterdã, ainda hoje emociona leitores no mundo inteiro. Seu diário narra os sentimentos, os medos e as pequenas alegrias de uma menina judia que, como sua família, lutou em vão para sobreviver ao Holocausto. Lançado em 1947, O diário de Anne Frank tornou-se um dos livros mais lidos do mundo. O relato tocante e impressionante das atrocidades e dos horrores cometidos contra os judeus faz deste livro um precioso documento e uma das obras mais importantes do século XX.'}, 
            {id:6, img: hyruleHistoria, titulo:'The Legend of Zelda: Hyrule História', autor:'Eiji Aonma', preco:185.00, descricao:'Dark Horse Books and Nintendo team up to bring you The Legend of Zelda: Hyrule Historia, containing an unparalleled collection of historical information on The Legend of Zelda franchise. This handsome hardcover contains never-before-seen concept art, the full history of Hyrule, the official chronology of the games, and much more! Starting with an insightful introduction by the legendary producer and video-game designer of Donkey Kong, Mario, and The Legend of Zelda, Shigeru Miyamoto, this book is crammed full of information about the storied history of Links adventures from the creators themselves! As a bonus, The Legend of Zelda: Hyrule Historia includes an exclusive comic by the foremost creator of The Legend of Zelda manga — Akira Himekawa!'},
            {id:7, img: homemDeGiz, titulo:'O Homem de Giz', autor:'C. J. Tudor', preco:34.90, descricao:'Assassinato e sinais misteriosos em uma trama para fãs de Stranger Things e Stephen King Em 1986, Eddie e os amigos passam a maior parte dos dias andando de bicicleta pela pacata vizinhança em busca de aventuras. Os desenhos a giz são seu código secreto: homenzinhos rabiscados no asfalto; mensagens que só eles entendem. Mas um desenho misterioso leva o grupo de crianças até um corpo desmembrado e espalhado em um bosque. Depois disso, nada mais é como antes. Em 2016, Eddie se esforça para superar o passado, até que um dia ele e os amigos de infância recebem um mesmo aviso: o desenho de um homem de giz enforcado. Quando um dos amigos aparece morto, Eddie tem certeza de que precisa descobrir o que de fato aconteceu trinta anos atrás. Alternando habilidosamente entre presente e passado, O Homem de Giz traz o melhor do suspense: personagens maravilhosamente construídos, mistérios de prender o fôlego e reviravoltas que vão impressionar até os leitores mais escaldados.'},
            {id:8, img: duna, titulo:'Duna', autor:'Frank Herbert', preco:84.90, descricao:'Uma estonteante mistura de aventura e misticismo, ecologia e política, este romance ganhador dos prêmios Hugo e Nebula deu início a uma das mais épicas histórias de toda a ficção científica. Duna é um triunfo da imaginação, que influenciará a literatura para sempre.Esta edição inédita, com introdução de Neil Gaiman, apresenta ao leitor o universo fantástico criado por Herbert e que será adaptado ao cinema por Denis Villeneuve, diretor de A chegada e de Blade Runner 2.'},
            {id:9, img: morroDosVentos, titulo:'O Morro dos Ventos Uivantes', autor:'Emily Brontë', preco:24.90, descricao:'"SE O AMOR DELA MORRESSE, eu arrancaria seu coração do peito e beberia seu sangue." O livro favorito do casal do momento: Bella e Edward! Na fazenda chamada Morro dos Ventos Uivantes nasce uma paixão devastadora entre Heathcliff e Catherine, amigos de infância e cruelmente separados pelo destino. Mas a união do casal é mais forte do que qualquer tormenta: um amor proibido que deixará rastros de ira e vingança. "Meu amor por Heathcliff é como uma rocha eterna. Eu sou Heathcliff", diz a apaixonada Cathy. O único romance escrito por Emily Brontë e uma das histórias de amor mais belas de todos os tempos, O morro dos ventos uivantes é um clássico da literatura inglesa e tornou-se o livro favorito de milhares de pessoas, inclusive dos belos personagens de Stephenie Meyer.'},
            {id:10, img: starWars, titulo:'Star Wars e a Filosofia', autor:'Jason Eberl', preco:42.90, descricao:'Atenção: Você deve esquecer tudo o que aprendeu até agora. Abra sua mente para uma nova galáxia. E que a força esteja com você. Star Wars e a Filosofia é um livro escrito por algumas das mentes mais brilhantes da galáxia, explorando o lado mais profundo de Star Wars e de seu universo expandido. Há um novo olhar sobre temas familiares, como a natureza da Força — é preciso existir um lado negro? — e uma reflexão acerca da representação das mulheres. Examinamos a importância filosófica por trás do impacto de Star Wars no mundo real como um artefato importante da cultura pop, o legado de Joseph Campbell sobre o alicerce mítico da saga, e oferecemos uma estrutura para a compreensão de todo o universo de Star Wars. Com o livro que você tem em mãos, o círculo está agora completo, e aqueles que um dia já foram alunos podem iniciar o caminho para se tornarem mestres jedis.'},
            {id:11, img: deusesAmericanos, titulo:'Deuses Americanos', autor:'Neil Gaiman', preco:59.90, descricao:'Obra-prima de Neil Gaiman, Deuses americanos é relançado pela Intrínseca com conteúdo extra, em Edição Preferida do Autor. “Deuses americanos” é, acima de tudo, um livro estranho. E foi essa estranheza que tornou o romance de Neil Gaiman, publicado pela primeira vez em 2001, um clássico imediato. Nesta nova edição, preferida do autor, o leitor encontrará capítulos revistos e ampliados, artigos, uma entrevista com Gaiman e um inspirado texto de introdução. A saga de Deuses americanos é contada ao longo da jornada de Shadow Moon, um ex-presidiário de trinta e poucos anos que acabou de ser libertado e cujo único objetivo é voltar para casa e para a esposa, Laura. Os planos de Shadow se transformam em poeira quando ele descobre que Laura morreu em um acidente de carro. Sem lar, sem emprego e sem rumo, ele conhece Wednesday, um homem de olhar enigmático que está sempre com um sorriso no rosto, embora pareça nunca achar graça de nada. Depois de apostas, brigas e um pouco de hidromel, Shadow aceita trabalhar para Wednesday e embarca em uma viagem tumultuada e reveladora por cidades inusitadas dos Estados Unidos, um país tão estranho para Shadow quanto para Gaiman. É nesses encontros e desencontros que o protagonista se depara com os deuses — os antigos (que chegaram ao Novo Mundo junto dos imigrantes) e os modernos (o dinheiro, a televisão, a tecnologia, as drogas) —, que estão se preparando para uma guerra que ninguém viu, mas que já começou. O motivo? O poder de não ser esquecido. O que Gaiman constrói em Deuses americanos é um amálgama de múltiplas referências, uma mistura de road trip, fantasia e mistério — um exemplo máximo da versatilidade e da prosa lúdica e ao mesmo tempo cortante de Neil Gaiman, que, ao falar sobre deuses, fala sobre todos nós. “Deuses americanos” foi adaptado para a TV em série com estreia prevista para 2017, com roteiro do próprio Neil Gaiman e produção de Bryan Fuller (das séries Hannibal e Pushing Daisies e dos filmes da franquia Star Trek). Juntos, os livros de Neil Gaiman lançados pela Intrínseca já venderam mais de 100 mil exemplares. “Original, arrebatador e infinitamente criativo.”'},
        ]
  }
  